body:
  - type: input
    attributes:
      name: api_token
      label: 'API Token:'
      defaultValue: ""
  - type: dropdown
    attributes:
      name: cache_ttl
      label: 'Cache duration:'
      defaultValue: '5 minutes'
      options:
        - '5 minutes'
        - '15 minutes'
        - '30 minutes'
        - '1 hour'
        - '6 hours'
        - '12 hours'
        - '1 day'
        - '3 days'
